### ISSUE TITLE
Font Size verändern

### ISSUE THREAD

**Issue by markusvoelter** [SimonWaldherr/wp-osf-shownotes#15]
Ich würde gerne die Schriftgröße der Chapter-Headings verkleinern (siehe Bild anbei - die sind zu groß!). Kannst Du mit bitte einen Tipp geben wo in den Sourcen (PHP bzw. CSS) ich da was ändern muss? Ich habe selber schon mal ein bisschen rumgeschaut, aber vor lauter Bäumen den Wald nicht gefunden.

![screen shot 2015-02-18 at 22 15 31](https://cloud.githubusercontent.com/assets/592330/6256851/bcf02a2e-b7bb-11e4-91b9-ec1f31da0572.png)

**Comment by SimonWaldherr** [comment]
Das Plugin ändert/definiert keine Schriftgrößen, nur Schriftarten und Positionen (und natürlich die Icons und so Dinge). Die Schriftgröße ergibt sich durch die CSS Definitionen des verwendeten Themes. 
Die Überschrift ist ein H2-Element innerhalb einiger DIVs und eines ARTICLEs.
So kann dann mittels ```article h2``` oder auch durch ```.osf_chapter``` die Überschrift (Kapitel) angesprochen werden.
Im konkreten Fall wird die Schriftgröße durch
```css
h2 {
font-size: 26px;
line-height: 30px;
}
```

aus Zeile 144 der style.css (http://omegataupodcast.net/wp-content/themes/designfolio-pro/style.css) definiert.
Entweder dies wird direkt im Theme geändert oder an einer anderen Stelle (separate CSS-Datei) überschrieben.

**Comment by markusvoelter** [comment]
Danke. Ich habe in der style_three.css (die ist bei mir aktiv) den folgenden Code eingebaut:

.osf_chapter {
  font-size: 16px;
}

Das tut soweit. Hast Du noch ne Idee wie man den großen Abstand *nach* der OSF-Chapter weg bekommt?

**Comment by SimonWaldherr** [comment]
ich würde ```.osf_items``` in Zeile 29 durch folgendes ersetzen:

```css
.osf_items {  
  padding-top: 0px;
  margin-top: 0px;
  margin-bottom: 0px;
  padding-bottom: 5px;
}
```

**Comment by markusvoelter** [comment]
Super, danke!

Zur Dokumentation des Ergebnisses für die Podcasterkollegen attache ich hier mal einen Screenshot des neuen Standes. 
![screen shot 2015-02-21 at 18 12 49](https://cloud.githubusercontent.com/assets/592330/6315049/6d5ed0d2-b9f5-11e4-834b-f8b038570886.png)
